### ISSUE TITLE
[Minor bug] Weird display when scaling is 150% instead of 100%

### ISSUE THREAD

**Issue by xpirad** [aka-katto/dandere2x#100]
Hello, i'm using a 2k display and using scale 150% on windows
![image](https://user-images.githubusercontent.com/24430064/73120608-87e34f00-3fab-11ea-9a4e-4e386ba82ebb.png)
However, under this setting, the gui displays abnormally like this
![image](https://user-images.githubusercontent.com/24430064/73120616-aa756800-3fab-11ea-9e75-1758a3d6cba7.png)

If i change the scaling to 100%, it went back to normal, but the font would be way too small without scaling.

**Comment by aka-katto** [comment]
hm, i have no clue how to even approach this. 

Thanks for letting me know.

**Comment by aka-katto** [comment]
Moving to gtk slowly. Hopefully this issue goes away
