### ISSUE TITLE
waifu2x-ncnn-vulkan not working

### ISSUE THREAD

**Issue by SnaxxNZ** [aka-katto/dandere2x#102]
Issue posted here as requested from: https://www.reddit.com/r/Dandere2x/comments/ea2w4m/could_not_upscale_first_file_check_logs_file_to/ffk628f?utm_source=share&utm_medium=web2x

Dandere2x Version 1.7.1

Process:
1 - Load dandere2x.exe as Administrator.
2 - Select video + settings
3 - Start Upscale

Console outputs the message "Could not upscale first file.. check logs file to see what's wrong"

Log Files - https://drive.google.com/open?id=14MP8whh5jwjniNirxEggb2-b45-R5-Mj

As a side note, if I try and run waifu2x-ncnn-vulkan from the externals dir on its own that doesnt work either, but if I download and run https://github.com/f11894/waifu2x-ncnn-vulkan-GUI/ that works just fine.

**Comment by aka-katto** [comment]
Is this issue specific to the regular show or dos it generalize to other files (namely the demo video provided) aswell?

**Comment by SnaxxNZ** [comment]
Its the same regardless of the file I use.

**Comment by aka-katto** [comment]
Is this issue consistent in 1.3.1 as well, or a strictly 1.7.1 issue?

**Comment by SnaxxNZ** [comment]
Sorry for the late reply.
The issue is present in both 1.3.1 and 1.7.1. I have also just tried 1.8 and its still happening.

**Comment by aka-katto** [comment]
Ouch - thanks for the heads up regarding the executable.

Is RAM an issue? this is my first guess, although there could be a lot wrong here on my end.

**Comment by SnaxxNZ** [comment]
Doesn't seem to be. I have 16GB system memory and 8GB of VRam (RTX 2070) and Task manager was only reporting about 5GB of memory being using used for the whole system, although given how slow everything was responding and refreshing I don't know how accurate that was.

I originally thought maybe it was "Windows Defender Real-Time protection" scanning all the video frames that was slowing everything down but after turning it off it was still doing it.

I have just run DDU and reinstalled my drivers just to see if that makes a difference and am going to try again later tonight.

**Comment by aka-katto** [comment]
> Doesn't seem to be. I have 16GB system memory and 8GB of VRam (RTX 2070) and Task manager was only reporting about 5GB of memory being using used for the whole system, although given how slow everything was responding and refreshing I don't know how accurate that was.
> 
> I originally thought maybe it was "Windows Defender Real-Time protection" scanning all the video frames that was slowing everything down but after turning it off it was still doing it.
> 
> I have just run DDU and reinstalled my drivers just to see if that makes a difference and am going to try again later tonight.
> 
> Edit: So reinstalling my drivers didn't help, but it looks like that fault is with waifu2x-ncnn-vulkan.exe and not dandere2x.
> 
> If I open up event viewer the it is full of error messages like the one below:
> 
> > Faulting application name: waifu2x-ncnn-vulkan.exe, version: 0.0.0.0, time stamp: 0x5e53c144
> > Faulting module name: nvoglv64.dll, version: 26.21.14.4250, time stamp: 0x5e543074
> > Exception code: 0xc0000005
> > Fault offset: 0x0000000000eb3f4b
> > Faulting process id: 0x600c
> > Faulting application start time: 0x01d5efc2780f668f

Sorry for the late reply, thanks for looking into it. This further presses for me to include a dummy d2x script to make sure all the external executable are working correctly.

**Comment by SnaxxNZ** [comment]
Bit more information... It seems like my GPU is faulty (Its crashing under heavy gaming loads). It seems stock Memory is clocked too high out of the box and requires a downclock of about 125MHz to become stable.

I haven't actually tested Waifu since figuring this out but if games are crashing because of memory it makes sense Waifu would cause issues as well being a memory intensive application.

**Comment by aka-katto** [comment]
> Bit more information... It seems like my GPU is faulty (Its crashing under heavy gaming loads). It seems stock Memory is clocked too high out of the box and requires a downclock of about 125MHz to become stable.
> 
> I haven't actually tested Waifu since figuring this out but if games are crashing because of memory it makes sense Waifu would cause issues as well being a memory intensive application.
> 
> Edit: The card I currently have (2070) is a loan card from a retail store while my regular card (Vega 56) is away being 'repaid'. It didn't even occur to me that the hardware might be faulty as I was running everything stock.

): Thanks for letting me know that graphics cards can affect waifu2x, this is good knowledge to know. I'll keep this in mind with future tickets
