### ISSUE TITLE
Video cannot be output

### ISSUE THREAD

**Issue by ROM256** [aka-katto/dandere2x#106]
![無題](https://user-images.githubusercontent.com/53605035/75150122-010ac900-5747-11ea-8009-2d63c4e22139.png)

**Comment by dona0712** [comment]
The problem is probably due to a quotation mark in the file name.
Change the name from `It"s time to Duel [HQ].mp4` to `Its time to Duel [HQ].mp4`.

**Comment by ROM256** [comment]
Thank you

**Comment by aka-katto** [comment]
> The problem is probably due to a quotation mark in the file name.
> Change the name from `It's time to Duel [HQ].mp4` to `Its time to Duel [HQ].mp4`.

Wow, I'll label this as a known bug now

**Comment by aka-katto** [comment]
No

**Comment by aka-katto** [comment]
Let me know if this fixes the issue

**Comment by ROM256** [comment]
Its time to Duel [HQ].mp4 name. Encode successfully
