### ISSUE TITLE
It deleted my suspended video

### ISSUE THREAD

**Issue by ANimeisbestu** [aka-katto/dandere2x#107]
Yeah It deleted the suspended video instead of continuing

**Comment by Tremeschin** [comment]
Resume feature not really working properly as it's kinda tricky to really _know_ where and how to resume; at least it somewhat works // in the past it was a dream.

Will keep in mind this as I quite like this feature, might do a code revision on it as I was out of the loop when aka_katto coded this. Thanks!!

**Comment by aka-katto** [comment]
Could you post a little more details? Could you replicate the error

**Comment by ANimeisbestu** [comment]
Is it really a error bc if u press suspend the button it suspends then if u press suspend again it crashes and if u try to load it deletes it and I tried it I got half progress again suspend but this time i just  upscale again still no resume

**Comment by aka-katto** [comment]
This isn't detailed enough for me to go off, could you explain step by step whats happening
