### ISSUE TITLE
Request: Linux/Debian version?

### ISSUE THREAD

**Issue by laundmo** [aka-katto/dandere2x#11]
hey there,

any chance to get a version that works on linux? i normally run all cudnn stuff on my ubuntu, so it would be nice not having to use windows for this.

i know you said its easier to release for windows, just putting this here to show theres interest

**Comment by Tremeschin** [comment]
On the project readme:

"Dandere2x is written natively on Ubuntu Linux but is ported and released on windows. I hope to have an official Linux release soon, but for the time being the windows version is easier to configure."

Guess we'll have to wait a little bit more =(

**Comment by laundmo** [comment]
> On the project readme:
> 
> "Dandere2x is written natively on Ubuntu Linux but is ported and released on windows. I hope to have an official Linux release soon, but for the time being the windows version is easier to configure."
> 
> Guess we'll have to wait a little bit more =(

just edited in that im aware of that and putting this here to show interest

**Comment by CardinalPanda** [comment]
> > On the project readme:
> > "Dandere2x is written natively on Ubuntu Linux but is ported and released on windows. I hope to have an official Linux release soon, but for the time being the windows version is easier to configure."
> > Guess we'll have to wait a little bit more =(
> 
> just edited in that im aware of that and putting this here to show interest


Hi,

thanks for letting me know there's interest, and thanks for all your comments / commits for code review.


Interestingly enough, I can't get Waifu2x to work On Ubuntu 18.04.. lol.

I have a spare hard drive I can put Ubuntu 16.04 on for development purposes, but I was planning on remaking Waifu2x for linux over the summer to work on latest Distros. Getting waifu2x to work on 16.04 alone was a hassle : \

**Comment by Tremeschin** [comment]
@CardinalPanda Well, I also had bad times getting the original waifu2x working but there's this other project named waifu2x-converter-cpp by DeadSix27 that just worked out of the box for me after I installed it through the Arch User Repository; even the CUDA package worked flawlessly. 

Not sure if it'll be hassle-free building from source on Ubuntu nor if it'll work for you or help on the dandere2x project. But I guess it's worth taking a look. Cheers!! :smiley:

**Comment by aka-katto** [comment]
works on linux now!
