### ISSUE TITLE
Could not upscale first file.. check logs file to see what's wrong - Ubuntu

### ISSUE THREAD

**Issue by gateway** [aka-katto/dandere2x#114]
```
(base) gateway@gateway-media:~/work/video/dandere2x/src$ /home/gateway/work/video/dandere2x/src
is not suspend file
output_file = /home/gateway/Desktop/videos/360_[vulkan][s2][n3][b20][q85].mp4
input_file = /home/gateway/Desktop/videos/360.mp4
block_size = 20
block_size = 20
image_quality = 85
waifu2x_type = vulkan
workspace = ../workspace/default/
log file is: /home/gateway/work/video/dandere2x/src/workspace/log_folder/dandere2x1586719611.9505394.log
is not resume session
Deleted Folder
threading at start of runtime
[<_MainThread(MainThread, started 139775800887104)>, <Dandere2x(dandere2x_thread, started 139775116351232)>]
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/encoded/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/residual_upscaled/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/compressed_moving/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/residual_images/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/merged/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/compressed_static/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/correction_data/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/inputs/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/pframe_data/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/debug/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/console_output/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/residual_data/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/fade_data/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/temp_image_folder/ 
Could not upscale first file.. check logs file to see what's wrong
```
Log file..

```
(base) gateway@gateway-media:~/work/video/dandere2x/src/workspace/log_folder$ tail -f dandere2x1586719611.9505394.log 
INFO:root:dandere2x joined called
INFO:dandere2xlib.utils.dandere2x_utils:/home/gateway/work/video/dandere2x/src/workspace/default/nosound.mp4 does not exist, waiting
INFO:wrappers.ffmpeg.progressive_frame_extractor_ffmpeg:extracting frames
INFO:root:Could not upscale first file.. check logs file to see what's wrong
INFO:root:Exiting Dandere2x.
```..

Ubuntu using waifux2x-ncc-valkan
```
(base) gateway@gateway-media:~/work/video/dandere2x/src/workspace/default$ /usr/bin/waifu2x-ncnn-vulkan -v
Usage: waifu2x-ncnn-vulkan -i infile -o outfile [options]...

  -h                   show this help
  -v                   verbose output
  -i input-path        input image path (jpg/png) or directory
  -o output-path       output image path (png) or directory
  -n noise-level       denoise level (-1/0/1/2/3, default=0)
  -s scale             upscale ratio (1/2, default=2)
  -t tile-size         tile size (>=32, default=400)
  -m model-path        waifu2x model path (default=models-cunet)
  -g gpu-id            gpu device to use (default=0)
  -j load:proc:save    thread count for load/proc/save (default=1:2:2)
  -x                   enable tta mode

```

(base) gateway@gateway-media:~/work/video/dandere2x/src/workspace/default$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

**Comment by aka-katto** [comment]
From recent memory, does waifu2x-ncnn-vulakn frrom the snap work? I remember I tried the snap on pop_os, and it wouldn't work correctly (Late September).

**Comment by gateway** [comment]
I compiled waifu2x-ncnn-vulakn from source.. any way I can get more debug info out of this.. the log file doesnt really seem to help.. is their a log or debug level?

**Comment by aka-katto** [comment]
> 
> 
> I compiled waifu2x-ncnn-vulakn from source.. any way I can get more debug info out of this.. the log file doesnt really seem to help.. is their a log or debug level?

are you referring to d2x or w2x_vulkan?

**Comment by gateway** [comment]
I'm trying to get down to the bottom of the issue why d2x is failing.. the log file doesnt have much in it.. any thoughts on upping logging or debug?

**Comment by aka-katto** [comment]
> I'm trying to get down to the bottom of the issue why d2x is failing.. the log file doesnt have much in it.. any thoughts on upping logging or debug?

Can you see if the waifu2x-ncnn-vulkan package you built will upscale an image correctly, via terminal? If it does, you may need to set the location of your waifu2x-ncnn-vulkan binary in the linux_config.yaml.

**Comment by gateway** [comment]
seems to work.. confirmed in photoshop the sizes.. 

```
(base) gateway@gateway-media:~/work/video/video2x/bin$ waifu2x-ncnn-vulkan
Usage: waifu2x-ncnn-vulkan -i infile -o outfile [options]...

  -h                   show this help
  -v                   verbose output
  -i input-path        input image path (jpg/png) or directory
  -o output-path       output image path (png) or directory
  -n noise-level       denoise level (-1/0/1/2/3, default=0)
  -s scale             upscale ratio (1/2, default=2)
  -t tile-size         tile size (>=32, default=400)
  -m model-path        waifu2x model path (default=models-cunet)
  -g gpu-id            gpu device to use (default=0)
  -j load:proc:save    thread count for load/proc/save (default=1:2:2)
  -x                   enable tta mode
(base) gateway@gateway-media:~/work/video/video2x/bin$ waifu2x-ncnn-vulkan -i ~/Desktop/t.jpg -o a.jpg -g 0 -n 1 -s 2 -m /home/gateway/work/video/waifu2x-ncnn-vulkan/models/models-cunet
[0 GeForce GTX 1080]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 GeForce GTX 1080]  buglssc=0  bugihfa=0
[0 GeForce GTX 1080]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
(base) gateway@gateway-media:~/work/video/video2x/bin$ ls -la a.jpg
-rw-r--r-- 1 gateway gateway 162596090 Apr 18 14:00 a.jpg
(base) gateway@gateway-media:~/work/video/video2x/bin$ ls -la ~/Desktop/t.jpg 
-rw-r--r-- 1 gateway gateway 19886675 Apr 17 18:18 /home/gateway/Desktop/t.jpg
```

**Comment by aka-katto** [comment]
Is your 'waifu2x-ncnn-vulkan_dir' pointed to the right place in the linux_config.yaml file?

**Comment by gateway** [comment]
yea the config file is properly set..

btw its dandere2x_linux.yaml unless im supposed to copy it to linux_config.yaml ?

config settings

```
waifu2x_ncnn_vulkan:

  waifu2x_ncnn_vulkan_file_name: waifu2x-ncnn-vulkan
  waifu2x_ncnn_vulkan_path: /usr/bin/

  output_options:
    -gpu: 0
    -load-proc-save_threads: null
    -model-path: /home/gateway/work/video/waifu2x-ncnn-vulkan/models/models-cunet
    -t: 256 # note: if you get black images try lowering this tile argument to some lower value.
    -verbose: null
```
```
(base) gateway@gateway-media:~/work/video/video2x/bin$ which waifu2x-ncnn-vulkan
/usr/bin/waifu2x-ncnn-vulkan
```
model path is valid, I also tried model path with null (default) same issue.

Any idea where I can print out the command line where its failing on Could not upscale first file.. check logs file to see what's wrong to see what the actual commands are being run.. maybe add some -verbose in it? thoughts

btw thank you for your time!

**Comment by gateway** [comment]
ugg.. ok looked at the log file again.. seems like something finally sitting out.. 

`INFO:root:dandere2x joined called
INFO:dandere2xlib.utils.dandere2x_utils:/home/gateway/work/video/dandere2x/src/workspace/default/nosound.mp4 does not exist, waiting
INFO:wrappers.ffmpeg.progressive_frame_extractor_ffmpeg:extracting frames
INFO:root:Could not upscale first file.. check logs file to see what's wrong
INFO:root:Exiting Dandere2x...
`
what is nosound.mp4 ?

**Comment by Tremeschin** [comment]
This last response log isn't telling anything useful for the "first file upscale" problem;; "nosound.mp4" is the mid-product of the upscale process, we store just the merged frames there and after everything has finished we put back the original audio into that video so that's the end result.

I'd say there's some syntax error within the waifu2x wrapper internal command?

Perhaps you can do two things, the second one if the first one doesn't tell anything:

1. Can you upload "workspace/console_output/vulkan_upscale_frame.txt" for us?
2. Add the line: `print(">>> W2X_VULKAN_COMAND:", exec_command)` just after the line 156 which is `os.chdir(waifu2x_ncnn_vulkan_path)` on the file `src/wrappers/waifu2x/waifu2x_vulkan.py `, and just before the `console_output = ...` line and search in the terminal the exec_command for waifu2x vulkan? (will start with the weirdo ">>> W2X_VULKAN_COMAND:" the line you're looking for)

**Comment by gateway** [comment]
```
(base) gateway@gateway-media:~/work/video/dandere2x/src$ python gui_driver.py 
/home/gateway/work/video/dandere2x/src
is not suspend file
output_file = /home/gateway/Desktop/videos/360_[vulkan][s2][n1][b20][q85].mp4
input_file = /home/gateway/Desktop/videos/360.mp4
block_size = 20
block_size = 20
image_quality = 85
waifu2x_type = vulkan
workspace = ../workspace/default/
log file is: /home/gateway/work/video/dandere2x/src/workspace/log_folder/dandere2x1587414027.8936286.log
is not resume session
Deleted Folder
threading at start of runtime
[<_MainThread(MainThread, started 139694844798784)>, <Dandere2x(dandere2x_thread, started 139694229640960)>]
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/console_output/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/residual_images/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/fade_data/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/encoded/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/inputs/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/residual_upscaled/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/temp_image_folder/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/compressed_static/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/correction_data/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/merged/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/debug/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/pframe_data/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/compressed_moving/ 
Successfully created the directory /home/gateway/work/video/dandere2x/src/workspace/default/residual_data/ 
>>> W2X_VULKAN_COMAND: ['/usr/bin/waifu2x-ncnn-vulkan', '-i', '/home/gateway/work/video/dandere2x/src/workspace/default/inputs/frame1.jpg', '-n', '1', '-s', '2', '-gpu', '0', '-model-path', '/home/gateway/work/video/waifu2x-ncnn-vulkan/models/models-cunet', '-t', '256', '-o', '/home/gateway/work/video/dandere2x/src/workspace/default/merged/merged_1.jpg']
Could not upscale first file.. check logs file to see what's wrong

```

**Comment by gateway** [comment]
` -model-path: /home/gateway/work/video/waifu2x-ncnn-vulkan/models/models-cunet`

seems to be the issue.. the command should be -m with the linux version 

https://github.com/nihui/waifu2x-ncnn-vulkan

`-m: /home/gateway/work/video/waifu2x-ncnn-vulkan/models/models-cunet`

works!

**Comment by aka-katto** [comment]
> made a change in the dandere2x_linux.yaml
> 
> ` -model-path: /home/gateway/work/video/waifu2x-ncnn-vulkan/models/models-cunet`
> 
> seems to be the issue.. the command should be -m with the linux version
> 
> https://github.com/nihui/waifu2x-ncnn-vulkan
> 
> `-m: /home/gateway/work/video/waifu2x-ncnn-vulkan/models/models-cunet`
> 
> works!

Will push this when I get the chance! Thanks for being patient w/ us on fixing this
