### ISSUE TITLE
Average of last 10 frames not displaying

### ISSUE THREAD

**Issue by StarSparkleNova** [aka-katto/dandere2x#116]
Currently stuck at 0.0 sec / frame.

V1.8
R9 290 gpu Vulkan only

**Comment by aka-katto** [comment]
Known bug, not really sure the origin of it. 

Will close thread when I find a fix.

**Comment by StarSparkleNova** [comment]
Which file in the source is it calculated in? I've been searching but can't find it.

**Comment by aka-katto** [comment]
https://github.com/aka-katto/dandere2x/blob/master/src/dandere2xlib/status.py

The status itself broke when I transitioned every dandere2x object to run as a thread, if that gives any intuition.
