### ISSUE TITLE
Width and Height swapped

### ISSUE THREAD

**Issue by Zarxrax** [aka-katto/dandere2x#123]
I loaded an old mpg file as the source video, it had a resolution of 352x240.
I did a 2x upscale and the output was 480*720.

Let me know if I can provide anything further.

**Comment by aka-katto** [comment]
What version of dandere2x?

**Comment by Zarxrax** [comment]
This was 1.8. Using Waifu2x-Vulcan, default settings.
Upon starting the conversion, the window displays this message:
```
Forcing Resizing to match blocksize..
New width -> 240
New height -> 360
```

**Comment by Tremeschin** [comment]
eeee? was the video content rotated or something? This could be ffprobe getting the wrong resolution because the video codec as you said it's an "old mpg"? Will check this whenever I can

**Comment by Zarxrax** [comment]
No it didn't get rotated, just stretched. I don't get this issue with a 320x240 resolution file, so it seems like its some sort of problem with it trying to match the block size. (by the way, wouldn't it make sense for the block sizes exposed in the gui to have multiples of 16 as options, since video files generally have a resolution that is a multiple of 16?)

I loaded the 352x240 video into ffprobe and it seems to detect it fine: 
Stream #0:1[0x1e0]: Video: mpeg1video, yuv420p(tv), 352x240 [SAR 200:219 DAR 880:657], 1856 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 29.97 tbc

**Comment by aka-katto** [comment]
> 
> 
> I loaded an old mpg file as the source video, it had a resolution of 352x240.
> I did a 2x upscale and the output was 480*720.
> 
> Let me know if I can provide anything further.

Couldn't replicate this issue, can you send me the video file somewhere (over reddit pm if you prefer privacy)?

**Comment by Zarxrax** [comment]
[Here ](https://drive.google.com/open?id=15zn5XtT2lhmh6H2Hj6OPfO5Gv4FXTsfp)is one of them.
I did some more testing as I have several files that are all the exact same format/resolution/framerate and everything. Some of them work fine but some of them get the height and width swapped.

**Comment by Tremeschin** [comment]
hmm interesting I ran the math that gets the best fitting resolution and it "guessed" the right one, 360x240, the closest one when block size is 20 (almost the same when block size is 16, 352x240), however I haven't looked deep into this issue yet.. quite busy lately with other projects :(

If you could give some more info like what block size you used..

Oh and by the time I was writing this you just commented lol, will test with this file you sent

**Comment by aka-katto** [comment]
Sorry for the slow response - I'm supposed to get email notifications whenever someone replies, but I didn't this week. 


I'm taking a hunch this is stemming from he buffer dimensions being 352x256, so dandere2x acts up. Investigating right now

**Comment by aka-katto** [comment]
I found the origin of the bug, it seems ffmpeg probes the video as being a different resolution, rather than the output stream. 

I'll try to implement some solution before the next patch, as this is a recurring bug, but at least we know where it comes from

**Comment by aka-katto** [comment]
Fixed the bug in commit

https://github.com/aka-katto/dandere2x/commit/9c9be92eb36e37105afaffcc28c3b28de9f291d9

Expect a new release soon.
