### ISSUE TITLE
add duration to 1.8

### ISSUE THREAD

**Issue by sparten9999** [aka-katto/dandere2x#125]
i was playing with 1.3.1 and after every job it said the duration. i don't see that same line in 1.8. is it possible to add that back?

**Comment by aka-katto** [comment]
I had no idea I removed this. Will do.

**Comment by treylar** [comment]
Not sure if it's related to this issue, but the "Average of Last 10 Frames" counter also hasn't been functioning for a while.

**Comment by aka-katto** [comment]
All issues in this thread fixed in 1.9
