### ISSUE TITLE
Dandere2x seems to ignore rotate property

### ISSUE THREAD

**Issue by DavisZeidaks** [aka-katto/dandere2x#131]
Hi!

I'm the one who had the problem with video ending up flipped as the output seemed to switch around the height & width properties. I've looked into it a bit more and after checking through the created folders, debug logs and reading the dandere2x source code I think I have found the issue. 

Sadly I don't currently run a ubuntu/arch setup so I can't really attempt to build a new version from source, but here's where I think the problem comes from:

During the final frames to video ffmpeg command at pipe.py the code runs a ffprobe analysis of the video, it reports that the video is 1088x1440 even though it seems to appear normal when watching it, turns out there's another stream property called "rotate" which is usually taken into account by media players. The rotate property for that video returns as 90 which means that what the settings read in as height & width should actually be flipped in this case.

I've done some manual runs of ffmpeg commands from the images in the created folders and the video output seems to be correct once you account for the rotate parameter.

**Comment by DavisZeidaks** [comment]
I think that I have found the solution to the problem, have tried to run both horizontal and vertical videos and the output seems correct everytime, opened a PR.

**Comment by aka-katto** [comment]
> 
> 
> I think that I have found the solution to the problem, have tried to run both horizontal and vertical videos and the output seems correct everytime, opened a PR.

Thank you, I'll be taking a look at it. This is a good catch since I wasn't really sure how to circumvent this ffprobe issue.

**Comment by aka-katto** [comment]
Solved in https://github.com/aka-katto/dandere2x/pull/132

: 3
