### ISSUE TITLE
Closes after Upscale

### ISSUE THREAD

**Issue by troy125478** [aka-katto/dandere2x#134]
I'm running the recent release and image quality is 85 and block size is 20. After i click "upscale" the program just closes. 
This is the log before it closes if it helps
![Annotation 2020-07-19 104000](https://user-images.githubusercontent.com/43628418/87881152-40fb7280-c9ac-11ea-8f9b-bef129279f8c.png)

**Comment by aka-katto** [comment]
Can you try running 1.9.5? 

https://github.com/aka-katto/dandere2x/releases/tag/1.9.5

**Comment by troy125478** [comment]
I used this and still get an error. this is the log.
![Annotation 2020-07-20 085029](https://user-images.githubusercontent.com/43628418/87958197-166df000-ca66-11ea-9b9f-2f45b503f2da.png)

**Comment by aka-katto** [comment]
It looks like the name is a potential issue. Try changing it to input_video.mkv or something, there seems to be non-ascii characters there

**Comment by troy125478** [comment]
Sure enough, that did it.
