### ISSUE TITLE
Black "boxes" in the finnished video.

### ISSUE THREAD

**Issue by starinspace** [aka-katto/dandere2x#139]
I do get some good frames but many upscaled frames gets big black "boxes" like in this image:
https://i.ytimg.com/vi/L1ZyfDzn0fk/maxresdefault.jpg

How do I get a "good pictures" without this black boxes?

**Comment by aka-katto** [comment]
I could conjecture that your tile size on waifu2x-ncnn-vulkan needs to be lowered. 

Edit line 115 to something lower and let me know if it still has issues.

https://github.com/aka-katto/dandere2x/blob/master/src/dandere2x_win32.yaml

**Comment by starinspace** [comment]
Yes, that did the trick. Thank you. 👍
