### ISSUE TITLE
Render gets stuck

### ISSUE THREAD

**Issue by MatPoot** [aka-katto/dandere2x#29]
Render starts, then after finishing the audio just gets stuck and does not proceed further

`INFO:context:Starting new dandere2x session
INFO:wrappers.waifu2x_caffe:manually upscaling file
INFO:wrappers.waifu2x_caffe:['C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\externals\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '-i', 'C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\inputs\\frame1.jpg', '-p', 'cudnn', '-n', '3', '-s', '2', '--gpu', '0', '-o', 'C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\merged\\merged_1.jpg']
INFO:context:Starting Threaded Processes..
INFO:wrappers.waifu2x_caffe:waifu2xcaffe session
INFO:wrappers.waifu2x_caffe:['C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\externals\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '-i', 'C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\differences\\', '-p', 'cudnn', '-n', '3', '-s', '2', '--gpu', '0', '-o', 'C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\upscaled\\']
INFO:dandere2x_core.merge:Upscaling frame 1
INFO:dandere2x_core.difference:('C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\', 1, 7320, 30)
INFO:wrappers.frame:C:\Users\Anon\Downloads\dandere0.7.3\0.7.3\demo_folder\date\upscaled\output_000001.png dne
INFO:wrappers.dandere2x_cpp:['C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\externals\\dandere2x_cpp.exe', 'C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\', '7320', '30', '4', 'n', '1', '.jpg']
INFO:dandere2x_core.difference:waiting on text
INFO:dandere2x_core.difference:<wrappers.frame.Frame object at 0x0000020D22EE9A90>
INFO:dandere2x_core.dandere2x_utils:C:\Users\Anon\Downloads\dandere0.7.3\0.7.3\demo_folder\date\inversion_data\inversion_1.txtdne, waiting
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.dandere2x_cpp:finished correctly
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:7319`

The longer I leave it the more of the same log statement it outputs.

sometimes inbetween that log it gives me this, then goes back to looping out that statement earlier

`INFO:dandere2x_core.dandere2x_utils:C:\Users\Anon\Downloads\dandere0.7.3\0.7.3\demo_folder\date\inversion_data\inversion_1.txtdne, waiting`

However this only seems to be the case for some... video files. Possibly broken?

**Comment by CardinalPanda** [comment]
definitely an issue related to video files. It seems Dandere2xCpp crashed (contrary to what the log file says - will fix to give better error messages)

Would you mind sending your video (maybe 2-3 seconds of it) so I can diagnose what's up?

**Comment by MatPoot** [comment]
Okay, with some further fiddling it seems to not be the video file, rather the length of the render. It works on some very long video files for 5 min, but when I ask it to convert the entire thing it crashes. My test video was the 1080p version, ep 4 from here. https://horriblesubs.info/shows/tate-no-yuusha-no-nariagari/

**Comment by CardinalPanda** [comment]
try like 1 minute less than what you were trying. I'd imagine the ffmpeg settings failed or something.

**Comment by MatPoot** [comment]
Same result, no fixes. Tried with 1 min less, 10 min less, it always gets stuck. Heres a look at the log file when that happens `INFO:wrappers.frame:C:\Users\Anon\Downloads\dandere0.7.3\0.7.3\demo_folder\date\upscaled\output_007317.png dne
INFO:dandere2x_core.merge:Upscaling frame 7318
INFO:dandere2x_core.merge:Upscaling frame 7319
INFO:context:Threaded Processes Finished succcesfully
INFO:context:Starting new dandere2x session
INFO:wrappers.waifu2x_caffe:manually upscaling file
INFO:wrappers.waifu2x_caffe:['C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\externals\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '-i', 'C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\inputs\\frame1.jpg', '-p', 'cudnn', '-n', '3', '-s', '2', '--gpu', '0', '-o', 'C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\merged\\merged_1.jpg']
INFO:context:Starting Threaded Processes..
INFO:wrappers.waifu2x_caffe:waifu2xcaffe session
INFO:wrappers.waifu2x_caffe:['C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\externals\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '-i', 'C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\differences\\', '-p', 'cudnn', '-n', '3', '-s', '2', '--gpu', '0', '-o', 'C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\upscaled\\']
INFO:dandere2x_core.merge:Upscaling frame 1
INFO:wrappers.frame:C:\Users\Anon\Downloads\dandere0.7.3\0.7.3\demo_folder\date\upscaled\output_000001.png dne
INFO:dandere2x_core.difference:('C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\', 1, 37080, 30)
INFO:wrappers.dandere2x_cpp:['C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\externals\\dandere2x_cpp.exe', 'C:\\Users\\Anon\\Downloads\\dandere0.7.3\\0.7.3\\demo_folder\\date\\', '37080', '30', '4', 'n', '1', '.jpg']
INFO:dandere2x_core.difference:waiting on text
INFO:dandere2x_core.difference:<wrappers.frame.Frame object at 0x0000023834178A90>
INFO:dandere2x_core.dandere2x_utils:C:\Users\Anon\Downloads\dandere0.7.3\0.7.3\demo_folder\date\inversion_data\inversion_1.txtdne, waiting
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:37079
INFO:wrappers.dandere2x_cpp:finished correctly
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:37079
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:37079
INFO:wrappers.waifu2x_caffe:Frames remaining before batch: 
INFO:wrappers.waifu2x_caffe:37079`

**Comment by CardinalPanda** [comment]
damn, that sucks.

I'm porting over video2x's ffmpeg wrapper to dandere2x. I'm not sure what's going on here but hopefully that'll fix the issue.

**Comment by CardinalPanda** [comment]
Works for me after restarting it. It seemed to stall for a moment. Do you still need help? We could hop in slack and figure it out if you do.
