### ISSUE TITLE
dandere2x just close instantly

### ISSUE THREAD

**Issue by tsukinnami** [aka-katto/dandere2x#41]
Exception: STATUS_ACCESS_VIOLATION at rip=0010043F0C1
rax=0000000000000000 rbx=0000000000000000 rcx=0000000000000001
rdx=000000A30000008B rsi=00000006000847D0 rdi=0000000000000000
r8 =0000000000000001 r9 =000000000000003C r10=0000000600095D60
r11=00000000000002D0 r12=00000000000004EC r13=0000000600084380
r14=00000006000963A0 r15=0000000000000001
rbp=000000000000C4E0 rsp=00000000FFFFC670
program=C:\Users\bad\Desktop\0.9\externals\dandere2x_cpp.exe, pid 11428, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
stackdump

**Comment by tsukinnami** [comment]
Hello Dandere!!
      3 [main] dandere2x_cpp 9420 cygwin_exception::open_stackdumpfile: Dumping stack trace to dandere2x_cpp.exe.stackdump

**Comment by aka-katto** [comment]
Sorry! I got a notification and I completely forgot to read this.

Could you post information regarding operating system / bit number? From what it looks like, cygwin isnt working correctly.
