### ISSUE TITLE
How do you select your dedicated gpu?

### ISSUE THREAD

**Issue by justinian-balaskas** [aka-katto/dandere2x#62]
I selected the vulkan port of waifu2x and dandere2x insists on using my integrated gpu instead of my dedicated one, I tried adding "-g": 1 or "-gpu-id": 1 to the json (found here https://github.com/nihui/waifu2x-ncnn-vulkan) but that just causes dandere2x to crash

**Comment by aka-katto** [comment]
is the vulkan in the folder legacy? The one on release may be outdated
