### ISSUE TITLE
[Suggestion] Support for anime4k?

### ISSUE THREAD

**Issue by xpirad** [aka-katto/dandere2x#71]
HI, i want to first say thank you for your continuous effort on this project!
It's really good and useful!

Also, i noticed that there is a new tool called anime4k supported by video2x now.
(https://github.com/bloc97/Anime4K)
It's said to be much faster than waifu2x, would you consider supporting this tool as well?
Anyway, just a small suggestion.

Thank you again!

**Comment by aka-katto** [comment]
Not for the time being.

It's on the back burner, but porting over his code to c++ is on my to-do list, but I have several issues with anime4k at large.

Thanks for the suggestion and support though! It's nice to see you still around.
