### ISSUE TITLE
Error in Qt5Core.dll while processing file

### ISSUE THREAD

**Issue by 57ar7up** [aka-katto/dandere2x#85]
dandere2x.exe

Description
Faulting Application Path: D:\AI\app\vision\upscale\Dandere2x\1.5.4\dandere2x.exe
Creation Time: 13.10.2019 22:28:40
Problem: Остановка работы
Status: Отчет отправлен

Problem signature
Problem Event Name:           BEX
Имя приложения:               dandere2x.exe
Версия приложения:            0.0.0.0
Отметка времени приложения:   5d24a31b
Имя модуля с ошибкой:         Qt5Core.dll
Версия модуля с ошибкой:      5.12.3.0
Отметка времени модуля с ошибкой: 5cac76e7
Смещение исключения:          00021b81
Код исключения:               c0000409
Данные исключения:            00000007

Extra information about the problem
Bucket ID: 69ad36af5c31c59d7334b5ee2de61bf1 (1383931020086483953)

**Comment by aka-katto** [comment]
Will look into tonight - this happened before.

Did 1.3.1 work for you?

**Comment by 57ar7up** [comment]
> Did 1.3.1 work for you?

Yes

**Comment by aka-katto** [comment]
https://github.com/aka-katto/dandere2x/releases/tag/0.1.5.6

I updated pyqt5 to be on a new module, I tested on my system and the .dll error didn't work. Let me know if it works for you.
