### ISSUE TITLE
[Suggestion + Question] Improve build for linux

### ISSUE THREAD

**Issue by Fadoli** [aka-katto/dandere2x#86]
Hey, few questions / suggestions here

1. Is it still possible to use that same build pattern for the lattest versions ? ( as described in https://github.com/aka-katto/dandere2x/releases/tag/0.1.4.5 )
1. Would you be interested in automating the build process ? (I'd)
1. Do you want me to make it into a small .sh file or anything like that, so that it download deps, and make it all ? (or a makefile even if you want)

**Comment by Tremeschin** [comment]
Hey thanks for the suggestion. We technically already have these two scripts to download / make deps on the download, I'm busy with college and so aka is so when we are a little more free we would implement these scripts.

**Comment by Tremeschin** [comment]
For reference:

[Build the cpp code](https://github.com/Tremeschin/dandere2x/blob/minimal-disk/src/linux_build.sh) sh script for Linux. This relies on the user having the clang stuff and compiler, (posix compliant shell?), etc;

[R&D ramdisk mode](https://github.com/Tremeschin/dandere2x/blob/minimal-disk/src/linux_ramdisk.sh) for my previous project structure to run d2x completely on RAM;

[Download deps for Windows](https://github.com/Tremeschin/dandere2x/blob/minimal-disk/src/d2x-deps-downloader.py) script I was working one before college stuff and code motivation on spare time.

Maybe you could make those scripts better and more reliable testing on different envs?

Perhaps the ramdisk mode need a workaround aka didn't implemented on current master for making a workspace/processing/ folder for the on the fly moving parts of Dandere2x. It's on that old branch on my fork these changes on the file `src/context.py`
