### ISSUE TITLE
Constantly getting stuck at "waiting for file (PATH)\framexx.jpg"

### ISSUE THREAD

**Issue by Mockedarche** [aka-katto/dandere2x#93]
I wanted to test this out as I got video2x working but it just takes too long. I don't need perfect results but want decent with some speed. Tried this out and when I used to gui to set everything up it all seems good but then after no more than 25 frames in it gives me this error. The frame file isn't there in the inputs directory so it's not a matter of not seeing it its a matter of failure to place or extract the frame. 
Windows 10 using the waifu2x-caffe type.
Let me know if there is anything else you want to know.
![b1c32314a4591c1307bc13d2dadb0574](https://user-images.githubusercontent.com/44336986/71453365-2760b800-2748-11ea-8580-6cafea412e9f.png)

**Comment by Mockedarche** [comment]
![image](https://user-images.githubusercontent.com/44336986/71457125-c2ae5900-2759-11ea-8446-3a30105c7e67.png)
This is the other cmd (with a different video file).

**Comment by Mockedarche** [comment]
note version 1.3.1 Vulkan works perfectly fine. I saw in 1.5.7 "Changed progress_frame_extraction to now only use ffmpeg, so no more cv2 dependency.

I'm curious to see if any bugs will arise, but I think this should be more consistent than that of cv2. This also fixes some bugs (I think) with frame rate and sound." 
Possibly this is causing my issue. who knows i'll be using 1.3.1 (it doesn't have this issue AT ALL) for now. I don't know how much slower vulkan is than caffe (I have a 1070ti) or if it even is. If anyone has any suggestions let me know otherwise at this point nothin more I can do on my side (at least without instruction).

**Comment by aka-katto** [comment]
Thanks for filing the complaint, I'll have a debugging session to see if I can replicate it tonight.

**Comment by aka-katto** [comment]
I believe the issue could stem from the lack of cudnn.dll, if I had to guess.

If you got the 'externals' from waifu2x-caffee in the 1.3.1 version and replaced it in the 1.6+, does it work?

**Comment by Mockedarche** [comment]
After replacing the externals from 1.3.1 version to 1.6 I get the same issue. Thanks for the suggestion!

**Comment by aka-katto** [comment]
could you upload the 'console logs' and the 'logs' folder in the workspace to pastebin? They can help me find the origin of the issue.

**Comment by mleeneg** [comment]
I was having this issue too I think I found the fix.

In the dandere2x_win32.yaml
under the "min_disk_settings" set "use_min_disk" to False

I kept getting stuck at the 20s but when I changed "max_frames_ahead" to 200 I get stuck at 200. Which led me to set "use_min_disk" to False.

Now to Figure out why this directory residual_upscaled is empty.

**Comment by aka-katto** [comment]
> I was having this issue too I think I found the fix.
> 
> In the dandere2x_win32.yaml
> under the "min_disk_settings" set "use_min_disk" to False
> 
> I kept getting stuck at the 20s but when I changed "max_frames_ahead" to 200 I get stuck at 200. Which led me to set "use_min_disk" to False.
> 
> Now to Figure out why this directory residual_upscaled is empty.

residual_upscaled being empty would allude to waifu2x not working, could you upload your logs and console_logs folder somewhere here?

**Comment by mleeneg** [comment]
Dandere2x Log: https://pastebin.com/0ddCkw7p
ffmpeg_extract_frames_console.txt: https://pastebin.com/YF2Q6t5e
vulkan_upscale_frame.txt: https://pastebin.com/Nq56YykB
vulkan_upscale_frames.txt: https://pastebin.com/nQ9Shc50

From my findings my residual_data folder empty so it can't compare it to the pframe data to create the residual_images for the residual_upscaled. So the program is basically waiting for residual_data to be created.

**Comment by aka-katto** [comment]
> Dandere2x Log: https://pastebin.com/0ddCkw7p
> ffmpeg_extract_frames_console.txt: https://pastebin.com/YF2Q6t5e
> vulkan_upscale_frame.txt: https://pastebin.com/Nq56YykB
> vulkan_upscale_frames.txt: https://pastebin.com/nQ9Shc50
> 
> From my findings my residual_data folder empty so it can't compare it to the pframe data to create the residual_images for the residual_upscaled. So the program is basically waiting for residual_data to be created.

I'm familiar with this bug, I think there was an issue when compiling dandere2x_cpp.exe.

Tonight i'll try to find time and upload a nightly. 

Also, from the looks of it, you're using 1.6.

Does this bug exist on 1.3.1?

**Comment by mleeneg** [comment]
So far I can use 1.3.1 just fine.

**Comment by aka-katto** [comment]
> 
> 
> So far I can use 1.3.1 just fine.

https://github.com/aka-katto/dandere2x/releases/tag/v0.1.7

Let me know if this build works, this includes the resume features

**Comment by mleeneg** [comment]
Seems to work on defaults. Resume feature seems to work too. Program crashes when I try to upscale a different video. So I had to tell it to create a new workspace or delete the old one.

**Comment by Mockedarche** [comment]
Alright 1.7 seems to work longer it still gets stuck. 
![image](https://user-images.githubusercontent.com/44336986/72053920-39cd0c80-3285-11ea-9f1f-a5cba5aa1e3b.png)
![image](https://user-images.githubusercontent.com/44336986/72054212-c7106100-3285-11ea-873d-e1032104df04.png)
The image thats at frame 83 is where im at. no matter how many times I start it well I end up stuck. The other cmd window that was taking the frames closed and now it seems to be stuck.

**Comment by Mockedarche** [comment]
Now I get this and then it instantly closes. This is right after I start the upscale 
![image](https://user-images.githubusercontent.com/44336986/72067244-7efe3800-329f-11ea-8d4d-39ac7fbb87f9.png)

**Comment by aka-katto** [comment]
> Alright 1.7 seems to work longer it still gets stuck.
> ![image](https://user-images.githubusercontent.com/44336986/72053920-39cd0c80-3285-11ea-9f1f-a5cba5aa1e3b.png)
> ![image](https://user-images.githubusercontent.com/44336986/72054212-c7106100-3285-11ea-873d-e1032104df04.png)
> The image thats at frame 83 is where im at. no matter how many times I start it well I end up stuck. The other cmd window that was taking the frames closed and now it seems to be stuck.
> Thing to note is that even though the cmd seems stuck my gpu is doing work like normal.
> ![image](https://user-images.githubusercontent.com/44336986/72054350-0e96ed00-3286-11ea-8ded-9dfd022195a8.png)

Got it - can you send the log folders for these also? I've never seen this error and want to get it working for you.

I suspect it's the move to min disk usage which might be causing problems

**Comment by aka-katto** [comment]
> 
> 
> Now I get this and then it instantly closes. This is right after I start the upscale
> ![image](https://user-images.githubusercontent.com/44336986/72067244-7efe3800-329f-11ea-8d4d-39ac7fbb87f9.png)

By the way, does deleting the workspace folder fix this issue? From the folder I can visibily see \residual_data\ failed to get created, which infers me to believe that the folder already existed, which I think can be problematic.

Also, thanks for being patient in reporting these bugs - they're really valuable for dandere2x's development.

**Comment by Mockedarche** [comment]
Alright im going to start on the top of your 2nd comment and work my way down.
Heres the logs before I do anything. https://mega.nz/#F!qDI0RA7I!fYkKwx4gbtLqukwf9vruYw 
When I deleted the workspace folder... and now the program just closes about 10 seconds after I click upscale. NO LOG was made. 
So before the program would work until it got would randomly stop updating now after I deleted the workspace folder the program closes seconds after opening. So I went ahead and redownloaded 1.7 and it STILL CLOSES a few seconds after clicking upscale. This always happens if I choose caffe. Vulkan works all the way to the end and then doesn't actually make the video. The output file is 0 bytes. 
So in short the program closes after clicking upscale if I choose caffe but works till the end with vulkan until it finally messes up at making the output. This picture is the cmd prompt 
![image](https://user-images.githubusercontent.com/44336986/72153260-a4a44380-336a-11ea-8d22-3102d11c0fc9.png)
Nothing changes it just sits there. 
I don't know if this error happens in C:/ as the reason I use the E:/ drive is because thats where my TEMP folder is because I use custom made software for cryptography and I need a large storage device for that. I can't test it on C because I can't change my TEMP location right now. 
Heres logs after everything i've done. https://mega.nz/#F!iKBm1CpR!RyLotkUj-FNJ9bNlmwRyAQ
It took around 12-15 minutes to supposedly do a 360p 3 minute video upscaled to a 2x factor. I was hoping this program would work for my needs but it seems like it wont. I was hoping to get somewhere near a 1 to 2 ratio at 1080p (aka 1hour video 2 hours to work up) but that doesn't seem possible yet. I hope these logs help you I don't think i'll continue trying to get this to work.

**Comment by aka-katto** [comment]
> This isn't to discourage you as I think the results when it does work is insanely amazing. Sadly I just don't think it would work for my needs even if I got it running the best I could.

No no its the opposite, this encourages me to maintain dandere2x lol, if no-one was trying to use it I would probably stop developing it. I'm actively trying to fix these bugs as they come up.

Could you send me the video you're trying to work with, if it's feasible? I'll try running it tonight. There's a general trend in dandere2x development where users have a really organic variety of videos they wish to upscale, and it's difficult for me to anticipate the behaviour of the different containers. 

I'll also try setting my temp to another drive as well to see if I can replicate some of these results, since this isn't the first time I've seen people do this and have run into errors - this is a good starting point for me to debug this issue.

**Comment by BanYiMeng** [comment]
I had the same problem

**Comment by Mockedarche** [comment]
NOTE after testing multiple video types (mp4 and mkv) along with different videos the same issues always persist. With 1.3.1 it finishes the upscale perfectly fine, with 1.6 it will stop somewhere after 20 frames with a message stating only that the frame file is missing (first picture), and finally with 1.7 caffe closes seconds after clicking upscale and vulkan finishes (or atleast seems to) the entire video but gets stuck at the end (like picture provided) with the video file being empty. 
![image](https://user-images.githubusercontent.com/44336986/72219871-22518600-3508-11ea-85de-75ed2e1e6f23.png)
If you want to send me a video and have me try it i'm perfectly able to do so. If you want any specifics about my computer just ask. Thank you for working on this issue for me.

**Comment by aka-katto** [comment]
> NOTE after testing multiple video types (mp4 and mkv) along with different videos the same issues always persist. With 1.3.1 it finishes the upscale perfectly fine, with 1.6 it will stop somewhere after 20 frames with a message stating only that the frame file is missing (first picture), and finally with 1.7 caffe closes seconds after clicking upscale and vulkan finishes (or atleast seems to) the entire video but gets stuck at the end (like picture provided) with the video file being empty.
> ![image](https://user-images.githubusercontent.com/44336986/72219871-22518600-3508-11ea-85de-75ed2e1e6f23.png)
> If you want to send me a video and have me try it i'm perfectly able to do so. If you want any specifics about my computer just ask. Thank you for working on this issue for me.

Yeah, send me the video you're using. 

I'm planning on adding more debugging print statements into the next build so I can help debug this issue, since I'm totally in the dark of what's causing it.

**Comment by Mockedarche** [comment]
well.. idk how I can constantly have new issues but now even with Vulkan the program closes not long after running. REGARDLESS of the video, i've tried movies, shows, youtube videos, mkv and mp4. https://mega.nz/#!zeBwxCTL Heres one of the videos its just something random I looked up that was short enough to not take forever. My specs are an r7 1700, 16 gb flare x 3200 mhz ram, an adata 120gb ssd, a 3 tb seagate external hdd, and a 1070ti.

**Comment by aka-katto** [comment]
I'm gonna buy an external hard drive and test this out.

**Comment by Mockedarche** [comment]
I downloaded the new version (released most recently) and now it seems to be working. I haven't finished a video yet but its going much further than before for the caffe method. Hopefully when it gets done upscaling it actually puts everything together. One thing I did notice is I'm still having the waiting for frame "issue". Should my gpu usage be going up and down like that? Should the extracted frame be so close to the currently being worked on frame? and for a video with a frame width of 512 and height of 384 should it be only at 1k frames after around 10 minutes? aka 2% (its a 24:23 second video) and the upscale is only 2x. It seems like your new bug fixes are making the program atleast more stable as right now idk if it will finish correctly I can at least get farther. NOTE: Nothing in my setup has changed not even gpu drivers.

**Comment by aka-katto** [comment]
> I downloaded the new version (released most recently) and now it seems to be working. I haven't finished a video yet but its going much further than before for the caffe method. Hopefully when it gets done upscaling it actually puts everything together. One thing I did notice is I'm still having the waiting for frame "issue". Should my gpu usage be going up and down like that? Should the extracted frame be so close to the currently being worked on frame? and for a video with a frame width of 512 and height of 384 should it be only at 1k frames after around 10 minutes? aka 2% (its a 24:23 second video) and the upscale is only 2x. It seems like your new bug fixes are making the program atleast more stable as right now idk if it will finish correctly I can at least get farther. NOTE: Nothing in my setup has changed not even gpu drivers.
> ![image](https://user-images.githubusercontent.com/44336986/73128049-c9adce80-3f86-11ea-82e3-76436cb10a19.png)

I'll address the points in a bullet style fashion:


## GPU Bouncing

Yeah, this is normal. It occurs whenever a new waifu2x session is started, and the way dandere2x inherently works, this happens a few times. You can reduce the amount of times a new session starts by setting 

```
max_frames_ahead: 20
``` 

To something higher. Now that I'm typing it, I plan on implementing a way to reduce this jumpy-ness for people who don't care about disk space usage, and would rather favor performance than using less HDD space.

Let me know if it finishes, it'll be a great benchmark / diagnosis for if 1.7.1 is stable or not. I've yet to do something more than 5k frames.

**Comment by Mockedarche** [comment]
The nightly build finished a video properly. I'm not sure why it gives me issues. But currently it seems to be working fine. I also took your suggestion about max frames and each frame takes less time to be rendered up. I also set reduce disk usage to False seems that makes it act like 1.31 were it does something before running. Overall everything seem rather stable. I am up scaling a different video now this one is around 22 minutes long. the res is extremely low so that's partly why my speed is to fast.

**Comment by Mockedarche** [comment]
Speed currently is 15 seconds per 1 second of video. Which is honestly not bad.

**Comment by Mockedarche** [comment]
Feel free to close this post as the bug has been fixed.

**Comment by Mockedarche** [comment]
ill leave this open for you to close aka-katto.

**Comment by StarSparkleNova** [comment]
I'm getting this problem with the new ssim binary. Does it on ocassion with 1.8 but gets stuck for a good 10 seconds on Ssim. R9 290 gpu.
