### ISSUE TITLE
denoise level setting is invalid

### ISSUE THREAD

**Issue by BanYiMeng** [aka-katto/dandere2x#95]
I set denoise level 0,but the program still using denoise level 3.
I try to delete noise0 model , but when I set denoise level 0 ,the program is still running.
when I delete noise3 model , i set denoise level 0/3,the program is crash.
I'm using waifu2x-ncnn-vulkan.
And I hope you can add some options to choice photo mode or anime mode.waifu2x-caffe has some model which is optimized for photo.

**Comment by aka-katto** [comment]
denoise level: Interesting bug, noted.

As for model, you can chose the model in the .yaml file itself, although it needs to manually be set.

**Comment by aka-katto** [comment]
Found the bug, will notify this thread when I update a release.

For the time being, changing the noise setting in the yaml is a quick solution.
