### ISSUE TITLE
When i upscale a vertical video , the lower side of the video will turn black

### ISSUE THREAD

**Issue by BanYiMeng** [aka-katto/dandere2x#97]
I try to upscale a 720(w)*1280(h) video , the lower side of the video will turn black with some flickering white spots.

![picture](https://user-images.githubusercontent.com/38632286/72220458-bfa1ce00-358b-11ea-9d26-e1ff8302023a.jpg)

`ffmpeg -i input.mp4 -metadata:s:v rotate="90" -codec copy output.mp4`
When I rotate the video using ffmpeg, the output returns to normal.

**Comment by aka-katto** [comment]
Side note before I replicate this -

Does dandere2x work for live action videos like this? I usually don't touch dandere2x when processing videos like this since it looks buggy.

**Comment by BanYiMeng** [comment]
For very low definition video, it works well.
But for ordinary definition video can produce a paint-like style.
I think it might have something to do with denoise.

**Comment by BanYiMeng** [comment]
For very low definition video, it works well.
But for ordinary definition video can produce a paint-like style.
I think it might have something to do with denoise.

**Comment by aka-katto** [comment]
Can you upload the video you're referring to, or a snippit of it? It'd be nice to be able to replicate this bug so I can figure it out myself.

**Comment by BanYiMeng** [comment]
https://1drv.ms/v/s!AoAnDCx_dskdsiOVjH1yVwlzUaqM?e=1glc1O
This is the video.

**Comment by aka-katto** [comment]
Was able to replicate the bug. Will leave bug up as I make progress on it

**Comment by aka-katto** [comment]
Fixed by @Tremeschin in 1.8
