### ISSUE TITLE
Python Exception on default settings

### ISSUE THREAD

**Issue by Gigaboy-01** [aka-katto/dandere2x#99]
I tried up-scaling a video and Python threw an exception in thread 'dandere2x_thread' and a type error . I'm not sure what's causing the problem and I changed the settings a few times, but I keep getting the same results. I have Python 3.7.3 installed on my PC.
![image](https://user-images.githubusercontent.com/31167933/72823422-4cf2bb80-3c39-11ea-8420-2e90e60db17c.png)

**Comment by aka-katto** [comment]
Are you running as administrator?

**Comment by aka-katto** [comment]
I believe I found the source of the issue, try out 1.7.1 and let me know if this issue persists

**Comment by Gigaboy-01** [comment]
I don't think I was running as admin, but I don't remember. Anyways I think it's fixed because I download 1.7.1 and it works. Thanks for the quick reply :D
